# Generated by Django 5.2.6 on 2025-10-19 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('therapeute', 'Therapeute')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='therapeute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.therapeute'),
        ),
        migrations.AlterField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.patient'),
        ),
    ]
