// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdJrQSIm29ZCd62AwGRR6HXmtrFBDx7k',
    appId: '1:349525324088:web:8773e49681696213db11cd',
    messagingSenderId: '349525324088',
    projectId: 'healme-820ba',
    authDomain: 'healme-820ba.firebaseapp.com',
    storageBucket: 'healme-820ba.firebasestorage.app',
    databaseURL: 'https://healme-820ba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXjuwkvqV2N_gPsOCevN8HazckIAkBBgQ',
    appId: '1:349525324088:android:644f15fcc14786d0db11cd',
    messagingSenderId: '349525324088',
    projectId: 'healme-820ba',
    storageBucket: 'healme-820ba.firebasestorage.app',
    databaseURL: 'https://healme-820ba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZO2Bb_VFzfKJgvgYfvzwr1tks9vEF7go',
    appId: '1:349525324088:ios:e325a8238c50b327db11cd',
    messagingSenderId: '349525324088',
    projectId: 'healme-820ba',
    storageBucket: 'healme-820ba.firebasestorage.app',
    iosBundleId: 'com.example.healmeFrontFlutter',
    databaseURL: 'https://healme-820ba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZO2Bb_VFzfKJgvgYfvzwr1tks9vEF7go',
    appId: '1:349525324088:ios:e325a8238c50b327db11cd',
    messagingSenderId: '349525324088',
    projectId: 'healme-820ba',
    storageBucket: 'healme-820ba.firebasestorage.app',
    iosBundleId: 'com.example.healmeFrontFlutter',
    databaseURL: 'https://healme-820ba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSdJrQSIm29ZCd62AwGRR6HXmtrFBDx7k',
    appId: '1:349525324088:web:1428f707616d5df0db11cd',
    messagingSenderId: '349525324088',
    projectId: 'healme-820ba',
    authDomain: 'healme-820ba.firebaseapp.com',
    storageBucket: 'healme-820ba.firebasestorage.app',
    databaseURL: 'https://healme-820ba-default-rtdb.firebaseio.com',
  );
}
