// lib/main.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'firebase_options.dart'; // *** IMPORTANT: This is the file generated by FlutterFire CLI ***

import 'services/auth_service.dart';
import 'pages/login_page.dart';
import 'pages/home_page.dart';

// 1. Change main to async
void main() async {
  // 2. Ensure Flutter bindings are initialized before calling native code
  WidgetsFlutterBinding.ensureInitialized();
  
  // 3. Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Use the generated options
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => AuthService()),
      ],
      child: MaterialApp(
        title: 'HealMe - Mental Health App',
        theme: ThemeData(
          fontFamily: "Montserrat",
          brightness: Brightness.dark,
          scaffoldBackgroundColor: const Color(0xFF0A0A12),
          colorScheme: const ColorScheme.dark( // Use const for ColorScheme
            primary: Color(0xFFFF64FF),
            secondary: Color(0xFF64C8FF),
            tertiary: Color(0xFFB450DC),
          ),
          bottomNavigationBarTheme: const BottomNavigationBarThemeData( // Use const
            backgroundColor: Color(0xFF1A1A2E),
            selectedItemColor: Color(0xFFFF64FF),
            unselectedItemColor: Colors.grey,
          ),
        ),
        // The FutureBuilder is correct for handling the initial auth check
        home: FutureBuilder(
          // Note: Creating a new AuthService().getUser() here will create a new instance 
          // every time the widget rebuilds. It's better to access the Provider instance 
          // or move this logic to a higher-level state management. For now, we leave 
          // it as is since it's checking authentication status once.
          future: AuthService().getUser(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return snapshot.hasData ? const HomePage() : const LoginPage();
            }
            // Show a progress indicator while waiting for Firebase and auth check to complete
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          },
        ),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}